version: '3.4'

services:
  bot:
    image: bot
    build:
      context: .
      dockerfile: DiscordBot/Dockerfile
    secrets:
      - Token
      - Prefix

secrets:
  Token:
    external: true
  Prefix:
    external: true