version: '3.4'

services:
  discordbot:
    image: ${DOCKER_REGISTRY-}discordbot
    build:
      context: .
      dockerfile: DiscordBot/Dockerfile
    secrets:
      - Token
      - Prefix

secrets:
  Token:
    external: true
  Prefix:
    external: true